name: build
on:
  pull_request:
    branches:
      - master
jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
        env:
          CI: true
      - run: yarn install
      - run: yarn lint
      - run: yarn test